"""empty message

Revision ID: c49d6f982f1e
Revises: 6f74d7a03fd3
Create Date: 2022-01-06 00:21:12.779437

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c49d6f982f1e'
down_revision = '6f74d7a03fd3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('request_id', sa.String(length=80), nullable=False),
    sa.Column('history', sa.Text(), nullable=True),
    sa.Column('model_name', sa.String(length=80), nullable=False),
    sa.Column('original_id', sa.Integer(), nullable=True),
    sa.Column('db_event_name', sa.String(length=80), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('user', sa.Column('first_name', sa.String(length=80), nullable=False))
    op.add_column('user', sa.Column('last_name', sa.String(length=120), nullable=False))
    op.drop_column('user', 'name')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('name', sa.VARCHAR(length=128), autoincrement=False, nullable=True))
    op.drop_column('user', 'last_name')
    op.drop_column('user', 'first_name')
    op.drop_table('audit_log')
    # ### end Alembic commands ###
